updated pom to use latest nsmenufx utility
this produces an error at execution:
org.osgi.framework.BundleException: Unresolved constraint in bundle
org.daisy.pipeline.gui [116]: Unable to resolve 116.0: missing
requirement [116.0] osgi.wiring.package;
(&(osgi.wiring.package=org.daisy.pipeline.clients)(version>=2.0.0)(!(ver
sion>=3.0.0)))